services:
  porto-arul:
    container_name: porto_arul_web
    image: ${REGISTRY_IMAGE:-registry.cihuyproject.my.id/portfolio-arul}:${IMAGE_TAG:-latest}
    pull_policy: always
    ports:
      - "${APP_PORT:-3003}:80"
    restart: unless-stopped
